/**
 * @module lib/blog-manifest
 * @description Canonical manifest of Anthropic customer blog post URLs.
 * Each entry maps a slug to its anthropic.com case study URL.
 * Used by blog-crawler.ts to fetch and cache raw customer anecdote data.
 *
 * Future use: simulate test scenarios based on real customer use cases
 * to validate Jade infrastructure against production patterns.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface BlogEntry {
  slug: string;
  title: string;
  url: string;
}

// ─── Manifest ───────────────────────────────────────────────────────────────

/** All 188 Anthropic customer blog posts. */
export const BLOG_MANIFEST: readonly BlogEntry[] = [
  { slug: "attention", title: "Attention automates sales operations and accelerates revenue with Claude", url: "https://www.anthropic.com/customers/attention" },
  { slug: "stripe", title: "Stripe deploys Claude Code to 1,370 engineers with zero-configuration enterprise rollout", url: "https://www.anthropic.com/customers/stripe" },
  { slug: "shortcut", title: "How Shortcut uses Opus 4.6 to tackle complex spreadsheet work for enterprises", url: "https://www.anthropic.com/customers/shortcut" },
  { slug: "athena-intelligence", title: "Athena Intelligence compresses weeks of enterprise knowledge work into hours with Claude", url: "https://www.anthropic.com/customers/athena-intelligence" },
  { slug: "n8n", title: "n8n turns natural language into workflow automations with Claude", url: "https://www.anthropic.com/customers/n8n" },
  { slug: "wiz", title: "Wiz migrates a 50,000-line codebase with Claude Code, achieving 2x performance gains", url: "https://www.anthropic.com/customers/wiz" },
  { slug: "lyft", title: "Lyft reduces customer support time by 87% with Claude", url: "https://www.anthropic.com/customers/lyft" },
  { slug: "pratham", title: "How Pratham delivers personalized assessment feedback to thousands of students across India with Claude", url: "https://www.anthropic.com/customers/pratham" },
  { slug: "adalat-ai", title: "Adalat AI makes India's court system accessible to millions with Claude", url: "https://www.anthropic.com/customers/adalat-ai" },
  { slug: "rocket", title: "Rocket generates agency-grade websites from a single prompt with Claude", url: "https://www.anthropic.com/customers/rocket" },
  { slug: "vambe", title: "Vambe powers conversational commerce across Latin America with Claude", url: "https://www.anthropic.com/customers/vambe" },
  { slug: "mintlify", title: "Mintlify ships 3x faster automating developer documentation with Claude", url: "https://www.anthropic.com/customers/mintlify" },
  { slug: "hubspot", title: "HubSpot reclaims time for creativity with Claude", url: "https://www.anthropic.com/customers/hubspot" },
  { slug: "figma", title: "Figma transforms ideas into interactive software with Claude", url: "https://www.anthropic.com/customers/figma" },
  { slug: "spotify", title: "Spotify cuts migration time by 90% with Claude Agent SDK", url: "https://www.anthropic.com/customers/spotify" },
  { slug: "vibecode", title: "Vibecode accelerates mobile app development with Claude", url: "https://www.anthropic.com/customers/vibecode" },
  { slug: "freedom-forever", title: "Freedom Forever automates permit workflows with Claude", url: "https://www.anthropic.com/customers/freedom-forever" },
  { slug: "medgate", title: "Medgate accelerates healthcare innovation with Claude Code", url: "https://www.anthropic.com/customers/medgate" },
  { slug: "gambit-robotics", title: "Gambit Robotics builds a real-time sous-chef with Claude", url: "https://www.anthropic.com/customers/gambit-robotics" },
  { slug: "workato", title: "Workato connects enterprise AI agents to business systems with Claude", url: "https://www.anthropic.com/customers/workato" },
  { slug: "greptile", title: "Greptile builds truly agentic code review with Claude Agent SDK", url: "https://www.anthropic.com/customers/greptile" },
  { slug: "money-forward", title: "Money Forward builds an AI-native engineering organization with Claude Code", url: "https://www.anthropic.com/customers/money-forward" },
  { slug: "carta-healthcare", title: "Carta Healthcare cuts clinical data processing time by 66% with Claude", url: "https://www.anthropic.com/customers/carta-healthcare" },
  { slug: "elation-health", title: "Elation Health delivers faster clinical insights with Claude", url: "https://www.anthropic.com/customers/elation-health" },
  { slug: "qualified-health", title: "Qualified Health and the University of Texas System use Claude to identify patients who need life-saving care", url: "https://www.anthropic.com/customers/qualified-health" },
  { slug: "banner-health", title: "Banner Health battles physician burnout with Claude-powered AI platform", url: "https://www.anthropic.com/customers/banner-health" },
  { slug: "base44", title: "Base44 uses Claude to transform app creation from weeks to hours for non-technical builders", url: "https://www.anthropic.com/customers/base44" },
  { slug: "crunched", title: "Crunched transforms Excel modeling for investors and advisors with Claude", url: "https://www.anthropic.com/customers/crunched" },
  { slug: "sett", title: "Sett scales gaming ad production with Claude", url: "https://www.anthropic.com/customers/sett" },
  { slug: "binti", title: "Binti modernizes child welfare systems with Claude", url: "https://www.anthropic.com/customers/binti" },
  { slug: "nevis", title: "Nevis accelerates advisor productivity with Claude", url: "https://www.anthropic.com/customers/nevis" },
  { slug: "zencoder", title: "Zencoder unlocks double-digit productivity gains with Claude Code SDK", url: "https://www.anthropic.com/customers/zencoder" },
  { slug: "emergent", title: "Emergent builds autonomous coding agents with Claude", url: "https://www.anthropic.com/customers/emergent" },
  { slug: "parcha", title: "How Parcha built a universal customer diligence agent in two weeks with Claude Agent SDK", url: "https://www.anthropic.com/customers/parcha" },
  { slug: "shopify", title: "How Shopify uses Anthropic's Claude on Google Cloud's Vertex AI to supercharge Sidekick", url: "https://www.anthropic.com/customers/shopify" },
  { slug: "matillion", title: "Matillion reduces data pipeline creation from 40 hours to 1 with Claude-powered AI assistant", url: "https://www.anthropic.com/customers/matillion" },
  { slug: "bunq", title: "bunq builds intelligent banking assistant Finn with Claude", url: "https://www.anthropic.com/customers/bunq" },
  { slug: "wordsmith", title: "Wordsmith uses Claude to transform legal operations from 4-day bottlenecks to 4-minute workflows", url: "https://www.anthropic.com/customers/wordsmith" },
  { slug: "ifs-nexus-black", title: "IFS Nexus Black builds industrial AI with Claude", url: "https://www.anthropic.com/customers/ifs-nexus-black" },
  { slug: "codewords", title: "CodeWords enables non-technical users to build workflow automations with Claude", url: "https://www.anthropic.com/customers/codewords" },
  { slug: "doctolib", title: "Doctolib accelerates developer productivity with Claude Code", url: "https://www.anthropic.com/customers/doctolib" },
  { slug: "n26", title: "N26 automates customer operations with Claude", url: "https://www.anthropic.com/customers/n26" },
  { slug: "loreal", title: "L'Oréal advances conversational analytics with Claude", url: "https://www.anthropic.com/customers/loreal" },
  { slug: "chronograph", title: "Chronograph scales operations and accelerates decision-making with Claude", url: "https://www.anthropic.com/customers/chronograph" },
  { slug: "hostinger", title: "Hostinger Helps Non-Technical Users Build a Website in Minutes with Claude", url: "https://www.anthropic.com/customers/hostinger" },
  { slug: "classmethod", title: "Classmethod accelerates development velocity with Claude Code", url: "https://www.anthropic.com/customers/classmethod" },
  { slug: "novo-nordisk", title: "Novo Nordisk accelerates clinical documentation and drug development with Claude", url: "https://www.anthropic.com/customers/novo-nordisk" },
  { slug: "jetbrains-multi-agent", title: "JetBrains Pioneers Multi-Agent IDE Experience with Claude Agent", url: "https://www.anthropic.com/customers/jetbrains-multi-agent" },
  { slug: "nbim", title: "NBIM accelerates sovereign wealth management with enterprise-wide AI transformation", url: "https://www.anthropic.com/customers/nbim" },
  { slug: "pelanor", title: "Pelanor delivers instant cloud cost insights with Claude", url: "https://www.anthropic.com/customers/pelanor" },
  { slug: "qodo", title: "Qodo helps developers ship quality code faster with Claude", url: "https://www.anthropic.com/customers/qodo" },
  { slug: "fountain", title: "Fountain accelerates frontline workforce hiring and management with Claude", url: "https://www.anthropic.com/customers/fountain" },
  { slug: "spring-new", title: "Spring.new empowers business application development with Claude on Google Cloud's Vertex AI", url: "https://www.anthropic.com/customers/spring-new" },
  { slug: "chatandbuild", title: "ChatAndBuild democratizes AI development globally with Claude", url: "https://www.anthropic.com/customers/chatandbuild" },
  { slug: "telus", title: "TELUS boosts workplace innovation with Claude", url: "https://www.anthropic.com/customers/telus" },
  { slug: "charm-industrial", title: "Charm Industrial accelerates carbon removal operations with Claude", url: "https://www.anthropic.com/customers/charm-industrial" },
  { slug: "cred", title: "CRED accelerates fintech development workflows with Claude", url: "https://www.anthropic.com/customers/cred" },
  { slug: "lindy", title: "Lindy empowers teams to scale with AI Agents powered by Claude", url: "https://www.anthropic.com/customers/lindy" },
  { slug: "rileybot", title: "RileyBot creates safe AI learning experiences for students with Claude", url: "https://www.anthropic.com/customers/rileybot" },
  { slug: "gradient-labs", title: "Gradient Labs transforms financial services customer support with Claude", url: "https://www.anthropic.com/customers/gradient-labs" },
  { slug: "circleback", title: "Circleback transforms meetings into structured insights with Claude", url: "https://www.anthropic.com/customers/circleback" },
  { slug: "tines", title: "Tines transforms workflow automation with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/tines" },
  { slug: "stubhub", title: "StubHub transforms live event ticketing with Claude", url: "https://www.anthropic.com/customers/stubhub" },
  { slug: "windsurf", title: "Windsurf enables collaborative software development agents with Claude", url: "https://www.anthropic.com/customers/windsurf" },
  { slug: "zapier", title: "Zapier builds an AI-first remote culture with Claude for Enterprise", url: "https://www.anthropic.com/customers/zapier" },
  { slug: "tahoe-lead-removal", title: "Tahoe Lead Removal Project cleans up Lake Tahoe with Claude", url: "https://www.anthropic.com/customers/tahoe-lead-removal" },
  { slug: "esentire", title: "eSentire scales elite cybersecurity expertise with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/esentire" },
  { slug: "legora", title: "Legora helps lawyers work more efficiently with Claude", url: "https://www.anthropic.com/customers/legora" },
  { slug: "grafana", title: "Grafana transforms observability workflows with Claude-powered multi-agent assistant", url: "https://www.anthropic.com/customers/grafana" },
  { slug: "dust", title: "Dust helps enterprises create actionable AI agents with MCP and Claude", url: "https://www.anthropic.com/customers/dust" },
  { slug: "classdojo", title: "ClassDojo saves teachers time with Claude", url: "https://www.anthropic.com/customers/classdojo" },
  { slug: "biomni", title: "Biomni accelerates biomedical discoveries by 100x with Claude", url: "https://www.anthropic.com/customers/biomni" },
  { slug: "audience-strategies", title: "Audience Strategies expands the electronic music industry's policy influence with Claude", url: "https://www.anthropic.com/customers/audience-strategies" },
  { slug: "dolly", title: "Dolly helps teachers reclaim their work-life balance with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/dolly" },
  { slug: "cubic", title: "cubic ships code 60x faster with Claude", url: "https://www.anthropic.com/customers/cubic" },
  { slug: "rakuten", title: "Rakuten accelerates development with Claude Code", url: "https://www.anthropic.com/customers/rakuten" },
  { slug: "brex", title: "Brex reimagines spend management with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/brex" },
  { slug: "mcgovern-foundation", title: "The Patrick J. McGovern Foundation standardizes grant evaluation with Claude", url: "https://www.anthropic.com/customers/mcgovern-foundation" },
  { slug: "harvey", title: "Harvey transforms legal work with Claude", url: "https://www.anthropic.com/customers/harvey" },
  { slug: "grab", title: "Grab scales personalized merchant support across Southeast Asia with Claude", url: "https://www.anthropic.com/customers/grab" },
  { slug: "solvely", title: "Solvely.ai transforms global learning with Claude", url: "https://www.anthropic.com/customers/solvely" },
  { slug: "apollo", title: "Apollo accelerates outbound sales at scale with Claude", url: "https://www.anthropic.com/customers/apollo" },
  { slug: "try", title: "TRY accelerates creative excellence with Claude", url: "https://www.anthropic.com/customers/try" },
  { slug: "genspark", title: "Genspark builds the future of AI agents with Claude", url: "https://www.anthropic.com/customers/genspark" },
  { slug: "nri", title: "NRI cuts document review time in half with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/nri" },
  { slug: "amira", title: "Amira helps millions of students master reading with the Science of Reading and Claude", url: "https://www.anthropic.com/customers/amira" },
  { slug: "bluenote", title: "Bluenote powers intelligent agents for life sciences with Claude", url: "https://www.anthropic.com/customers/bluenote" },
  { slug: "jetbrains-bedrock", title: "JetBrains builds developer tools with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/jetbrains-bedrock" },
  { slug: "sendbird", title: "Sendbird delivers reliable, enterprise-grade AI customer service with Claude", url: "https://www.anthropic.com/customers/sendbird" },
  { slug: "vanta", title: "Vanta streamlines compliance remediation with Claude", url: "https://www.anthropic.com/customers/vanta" },
  { slug: "benchling", title: "Benchling accelerates scientific discovery with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/benchling" },
  { slug: "triple-whale", title: "Triple Whale drives business growth with Claude", url: "https://www.anthropic.com/customers/triple-whale" },
  { slug: "futurehouse", title: "FutureHouse powers scientific discovery agents with Claude", url: "https://www.anthropic.com/customers/futurehouse" },
  { slug: "ramp", title: "How Ramp's engineering operates at hyperspeed with Claude Code", url: "https://www.anthropic.com/customers/ramp" },
  { slug: "lotte", title: "Lotte Homeshopping improves QA efficiency and partner satisfaction with Claude and Sendbird", url: "https://www.anthropic.com/customers/lotte" },
  { slug: "lokalise", title: "Lokalise improves translation quality with Claude", url: "https://www.anthropic.com/customers/lokalise" },
  { slug: "ig-group", title: "IG Group boosts productivity and saves operational costs with Claude for Work", url: "https://www.anthropic.com/customers/ig-group" },
  { slug: "trellix", title: "Trellix deploys autonomous security agents with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/trellix" },
  { slug: "panther", title: "Panther launches AI security teams can trust, powered by Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/panther" },
  { slug: "panorama", title: "Panorama unlocks student success with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/panorama" },
  { slug: "semgrep", title: "How Semgrep delivers AI-powered code security with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/semgrep" },
  { slug: "cox-automotive", title: "Cox Automotive transforms car sales with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/cox-automotive" },
  { slug: "quillit", title: "Quillit eliminates 80% of the time-consuming tasks of qualitative research using Claude", url: "https://www.anthropic.com/customers/quillit" },
  { slug: "block", title: "Block improves employee productivity and data access with Claude in Databricks", url: "https://www.anthropic.com/customers/block" },
  { slug: "quantium", title: "Quantium drives company-wide AI adoption with Claude", url: "https://www.anthropic.com/customers/quantium" },
  { slug: "canva", title: "Canva empowers employees across teams with Claude", url: "https://www.anthropic.com/customers/canva" },
  { slug: "rising-academies", title: "Rising Academies' chatbot tutors reach 150,000+ students across Sub-Saharan Africa with Claude", url: "https://www.anthropic.com/customers/rising-academies" },
  { slug: "tidio", title: "Tidio automates customer support at scale with Claude", url: "https://www.anthropic.com/customers/tidio" },
  { slug: "chatbase", title: "Chatbase helps companies deliver instant, personalized customer support with Claude", url: "https://www.anthropic.com/customers/chatbase" },
  { slug: "lovable", title: "Lovable helps anyone create software 20x faster with Claude", url: "https://www.anthropic.com/customers/lovable" },
  { slug: "pensive", title: "Pensive offers personalized AI teaching assistants for higher ed with Claude", url: "https://www.anthropic.com/customers/pensive" },
  { slug: "super-teacher", title: "Super Teacher offers elementary schools a personalized AI Tutor with Claude", url: "https://www.anthropic.com/customers/super-teacher" },
  { slug: "sentry", title: "Sentry helps developers accelerate debugging and ship fixes faster with Claude", url: "https://www.anthropic.com/customers/sentry" },
  { slug: "bito", title: "Bito powers agentic AI tools for software development with Claude", url: "https://www.anthropic.com/customers/bito" },
  { slug: "augment", title: "Augment unlocks complex codebases with Claude on Google Cloud's Vertex AI", url: "https://www.anthropic.com/customers/augment" },
  { slug: "praxis-ai", title: "Praxis AI pioneers AI-driven education with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/praxis-ai" },
  { slug: "aura-intelligence", title: "Aura Intelligence enhances decision intelligence with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/aura-intelligence" },
  { slug: "sk-telecom", title: "SK Telecom enhances customer support for millions of Koreans with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/sk-telecom" },
  { slug: "section", title: "Section helps companies navigate AI transformation with Claude", url: "https://www.anthropic.com/customers/section" },
  { slug: "alexa-plus", title: "Claude and Alexa+", url: "https://www.anthropic.com/customers/alexa-plus" },
  { slug: "orange", title: "Orange localizes manga at an unprecedented scale with Claude", url: "https://www.anthropic.com/customers/orange" },
  { slug: "launchnotes", title: "LaunchNotes pioneers next-gen engineering team productivity with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/launchnotes" },
  { slug: "replit", title: "Replit democratizes software development with Claude on Google Cloud's Vertex AI", url: "https://www.anthropic.com/customers/replit" },
  { slug: "campfire", title: "Campfire accelerates accounting with Claude", url: "https://www.anthropic.com/customers/campfire" },
  { slug: "snowflake", title: "Snowflake powers enterprise data intelligence with Claude", url: "https://www.anthropic.com/customers/snowflake" },
  { slug: "amazon-q-connect", title: "Amazon Q in Connect transforms customer service for agents and customers with Claude", url: "https://www.anthropic.com/customers/amazon-q-connect" },
  { slug: "micro1", title: "micro1 transforms technical recruiting with Claude", url: "https://www.anthropic.com/customers/micro1" },
  { slug: "thomson-reuters", title: "Thomson Reuters enhances tax guidance with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/thomson-reuters" },
  { slug: "advolve", title: "Advolve automates digital marketing with Claude", url: "https://www.anthropic.com/customers/advolve" },
  { slug: "kodif", title: "Kodif transforms customer support into a revenue center with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/kodif" },
  { slug: "appfolio", title: "AppFolio streamlines property management communication with Claude in Amazon Bedrock", url: "https://www.anthropic.com/customers/appfolio" },
  { slug: "law-and-company", title: "Law&Company transforms legal services in South Korea with Claude", url: "https://www.anthropic.com/customers/law-and-company" },
  { slug: "assembled", title: "Assembled transforms support operations with Claude", url: "https://www.anthropic.com/customers/assembled" },
  { slug: "university-of-sydney", title: "The University of Sydney and Accenture accelerate whale conservation with Claude", url: "https://www.anthropic.com/customers/university-of-sydney" },
  { slug: "brand-ai", title: "Brand.ai uses AI to make brands more human with Claude", url: "https://www.anthropic.com/customers/brand-ai" },
  { slug: "stairwell", title: "Stairwell protects companies from sophisticated cybersecurity threats with Claude", url: "https://www.anthropic.com/customers/stairwell" },
  { slug: "skillfully", title: "Skillfully transforms hiring through AI-powered skill simulations with Claude", url: "https://www.anthropic.com/customers/skillfully" },
  { slug: "newfront", title: "Newfront modernizes insurance experiences with Claude", url: "https://www.anthropic.com/customers/newfront" },
  { slug: "coderabbit", title: "CodeRabbit revolutionizes code review with Claude", url: "https://www.anthropic.com/customers/coderabbit" },
  { slug: "tldv", title: "tl;dv boosts revenue 500% from AI-powered meeting intelligence with Claude", url: "https://www.anthropic.com/customers/tldv" },
  { slug: "otter", title: "Otter transforms meetings into lasting organizational knowledge with Claude", url: "https://www.anthropic.com/customers/otter" },
  { slug: "palo-alto-networks", title: "Palo Alto Networks accelerates secure software development with Claude and Google Cloud", url: "https://www.anthropic.com/customers/palo-alto-networks" },
  { slug: "graphite", title: "Graphite speeds up code review by 40x with Claude", url: "https://www.anthropic.com/customers/graphite" },
  { slug: "intercom", title: "Intercom provides customer service tech that delivers up to 86% resolution rates with Claude", url: "https://www.anthropic.com/customers/intercom" },
  { slug: "studyfetch", title: "StudyFetch powers AI-driven personalized learning for millions of students with Claude", url: "https://www.anthropic.com/customers/studyfetch" },
  { slug: "humach", title: "Humach enhances AI-powered customer experience solutions with Claude", url: "https://www.anthropic.com/customers/humach" },
  { slug: "hume-ai", title: "Hume AI creates emotionally intelligent voice interactions with Claude", url: "https://www.anthropic.com/customers/hume-ai" },
  { slug: "aes", title: "AES accelerates renewable energy adoption with Claude on Google Cloud's Vertex AI", url: "https://www.anthropic.com/customers/aes" },
  { slug: "local-falcon", title: "Local Falcon helps 95,000 businesses boost search rankings with Claude", url: "https://www.anthropic.com/customers/local-falcon" },
  { slug: "lazy-ai", title: "Lazy AI speeds up internal software development for businesses who are adopting AI software with Claude", url: "https://www.anthropic.com/customers/lazy-ai" },
  { slug: "stackblitz", title: "StackBlitz achieves $4M ARR in 4 weeks for their AI web development platform with Claude", url: "https://www.anthropic.com/customers/stackblitz" },
  { slug: "coinbase", title: "Coinbase enhances customer support and operational efficiency with Claude", url: "https://www.anthropic.com/customers/coinbase" },
  { slug: "asana", title: "Asana supercharges work management with Claude", url: "https://www.anthropic.com/customers/asana" },
  { slug: "asapp", title: "ASAPP brings human-level AI to customer service with Claude", url: "https://www.anthropic.com/customers/asapp" },
  { slug: "braintrust", title: "Braintrust revolutionizes talent acquisition and career growth with Claude", url: "https://www.anthropic.com/customers/braintrust" },
  { slug: "hebbia", title: "Hebbia helps knowledge workers save thousands of hours with Claude", url: "https://www.anthropic.com/customers/hebbia" },
  { slug: "tabnine", title: "Tabnine solves developers' pain points and enhances productivity with Claude", url: "https://www.anthropic.com/customers/tabnine" },
  { slug: "you-com", title: "You.com enhances search and productivity with Claude", url: "https://www.anthropic.com/customers/you-com" },
  { slug: "blueflame-ai", title: "BlueFlame AI empowers lean investment teams to achieve institutional-scale analysis with Claude", url: "https://www.anthropic.com/customers/blueflame-ai" },
  { slug: "inscribe", title: "Inscribe cut time spent on fraud review 20x with Claude", url: "https://www.anthropic.com/customers/inscribe" },
  { slug: "wrtn", title: "WRTN pioneers AI entertainment and storytelling across Asia with Claude", url: "https://www.anthropic.com/customers/wrtn" },
  { slug: "decagon", title: "Decagon delivers white-glove customer service at scale with Claude", url: "https://www.anthropic.com/customers/decagon" },
  { slug: "notion", title: "Notion creates more intelligent workspaces with Claude", url: "https://www.anthropic.com/customers/notion" },
  { slug: "magicschool", title: "MagicSchool transforms K-12 education for 7 million educators and their students with Claude", url: "https://www.anthropic.com/customers/magicschool" },
  { slug: "zapia", title: "Zapia powers local commerce for millions across Latin America with Claude and Google Cloud's Vertex AI", url: "https://www.anthropic.com/customers/zapia" },
  { slug: "zoom", title: "Zoom AI Companion boosts user engagement and satisfaction with Claude", url: "https://www.anthropic.com/customers/zoom" },
  { slug: "tome", title: "Tome uncovers strategic insights for sales teams with Claude", url: "https://www.anthropic.com/customers/tome" },
  { slug: "cove", title: "Cove creates the future of visual AI collaboration with Claude", url: "https://www.anthropic.com/customers/cove" },
  { slug: "headstart", title: "Headstart accelerates software development by up to 100x with Claude", url: "https://www.anthropic.com/customers/headstart" },
  { slug: "gumroad", title: "Gumroad's customer support team ships code with Claude", url: "https://www.anthropic.com/customers/gumroad" },
  { slug: "gitlab", title: "GitLab powers stable, secure software development with Claude", url: "https://www.anthropic.com/customers/gitlab" },
  { slug: "armanino", title: "Armanino builds AI-powered accounting tools with Claude", url: "https://www.anthropic.com/customers/armanino" },
  { slug: "lex", title: "Lex streamlines the writing process with Claude", url: "https://www.anthropic.com/customers/lex" },
  { slug: "gitlab-productivity", title: "GitLab enhances productivity with Claude", url: "https://www.anthropic.com/customers/gitlab-productivity" },
  { slug: "sourcegraph", title: "Sourcegraph streamlines product and community insights with Claude", url: "https://www.anthropic.com/customers/sourcegraph" },
  { slug: "sourcegraph-cody", title: "Sourcegraph enhances the intelligence and speed of their AI-powered coding assistant with Claude", url: "https://www.anthropic.com/customers/sourcegraph-cody" },
  { slug: "wedia", title: "Wedia Group advances digital asset management with Claude", url: "https://www.anthropic.com/customers/wedia" },
  { slug: "pulpit-ai", title: "Pulpit AI turns sermons into multiple pieces of content with Claude", url: "https://www.anthropic.com/customers/pulpit-ai" },
  { slug: "intuit", title: "Intuit helps millions of customers confidently file taxes with federal tax explainers powered by Claude", url: "https://www.anthropic.com/customers/intuit" },
  { slug: "scribd", title: "Scribd, Inc. boosts content discovery and engagement with Claude", url: "https://www.anthropic.com/customers/scribd" },
  { slug: "copy-ai", title: "Copy.ai accelerates content creation and reduces costs with Claude", url: "https://www.anthropic.com/customers/copy-ai" },
  { slug: "steno", title: "Steno helps attorneys find the critical insights in legal transcripts with Claude", url: "https://www.anthropic.com/customers/steno" },
  { slug: "jumpcut", title: "Jumpcut helps Hollywood find the next big script with Claude", url: "https://www.anthropic.com/customers/jumpcut" },
  { slug: "clay", title: "Clay generates personalized sales outreach at scale with Claude", url: "https://www.anthropic.com/customers/clay" },
  { slug: "gamma", title: "Gamma helps teams create polished presentations with Claude", url: "https://www.anthropic.com/customers/gamma" },
  { slug: "factory", title: "Factory is building Droids for software engineering with Claude", url: "https://www.anthropic.com/customers/factory" },
  { slug: "brian-impact", title: "Brian Impact Foundation powers their search for the next generation of social innovators with Claude", url: "https://www.anthropic.com/customers/brian-impact" },
  { slug: "perplexity", title: "Perplexity delivers factual and relevant answers with Claude", url: "https://www.anthropic.com/customers/perplexity" },
] as const;

/** Total count for validation. */
export const BLOG_COUNT = BLOG_MANIFEST.length;

/** Get all blog URLs. */
export function getBlogUrls(): string[] {
  return BLOG_MANIFEST.map((b) => b.url);
}

/** Get blog entry by slug. */
export function getBlogBySlug(slug: string): BlogEntry | undefined {
  return BLOG_MANIFEST.find((b) => b.slug === slug);
}
